export const SUI_USDC_TYPE =
  '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC';

export const SUI_USDC_TESTNET_TYPE =
  '0xa1ec7fc00a6f40db9693ad1415d0c193ad3906494428cf252621037bd7117e29::usdc::USDC';

export const KNOWN_SUI_CURRENCIES = new Set([SUI_USDC_TYPE, SUI_USDC_TESTNET_TYPE]);

export const SUI_ADDRESS_REGEX = /^0x[a-fA-F0-9]{1,64}$/;

export const VALIDATION_CODES = {
  OPENAPI_FETCH_FAILED: 'OPENAPI_FETCH_FAILED',
  OPENAPI_PARSE_FAILED: 'OPENAPI_PARSE_FAILED',
  OPENAPI_VERSION_INVALID: 'OPENAPI_VERSION_INVALID',
  NO_PAID_ENDPOINTS: 'NO_PAID_ENDPOINTS',
  MISSING_402_RESPONSE: 'MISSING_402_RESPONSE',
  MISSING_REQUEST_BODY: 'MISSING_REQUEST_BODY',
  MISSING_PROTOCOLS: 'MISSING_PROTOCOLS',
  PROTOCOL_NOT_MPP: 'PROTOCOL_NOT_MPP',
  MISSING_PRICING: 'MISSING_PRICING',
  INVALID_PRICE_FORMAT: 'INVALID_PRICE_FORMAT',
  MISSING_GUIDANCE: 'MISSING_GUIDANCE',
  HIGH_ROUTE_COUNT: 'HIGH_ROUTE_COUNT',
  PROBE_FAILED: 'PROBE_FAILED',
  PROBE_NOT_402: 'PROBE_NOT_402',
  PROBE_INVALID_RECIPIENT: 'PROBE_INVALID_RECIPIENT',
  PROBE_UNKNOWN_CURRENCY: 'PROBE_UNKNOWN_CURRENCY',
  PROBE_REALM_MISMATCH: 'PROBE_REALM_MISMATCH',
} as const;
